import esbuild from "esbuild";
import process from "process";
import builtins from 'builtin-modules'
import 'dotenv/config'
import fs from 'fs';
import path from "path";
console.log(process.env.OUTPUT_FILE)
const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

esbuild.build({
	banner: {
		js: banner,
	},
	entryPoints: ['main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	watch: !prod,
	target: 'es2020',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: process.env.OUTPUT_FILE || 'main.js',
})
.catch(() => process.exit(1))
.finally(() => {
	
	const buildTarget = path.dirname(process.env.OUTPUT_FILE) +'manifest.json';
	console.log(`Copying manifest to: ` + buildTarget)
	fs.copyFileSync('./manifest.json',  buildTarget)
});
